export enum DeliveryInfoStatus {
  PENDING = 'PENDING',
  CANCELED = 'CANCELED',
  RESULTS_AVAILABLE = 'RESULTS_AVAILABLE',
  WAITING_FOR_DATA_SET = 'WAITING_FOR_DATA_SET',
  FETCHED_BY_RESEARCHER = 'FETCHED_BY_RESEARCHER',
}
