export enum DueDateEnum {
  DUE_DAYS_FDPG_CHECK = 'DUE_DAYS_FDPG_CHECK',
  DUE_DAYS_DATA_CORRUPT = 'DUE_DAYS_DATA_CORRUPT',
  DUE_DAYS_FINISHED_PROJECT = 'DUE_DAYS_FINISHED_PROJECT',
  DUE_DAYS_LOCATION_CHECK = 'DUE_DAYS_LOCATION_CHECK',
  DUE_DAYS_EXPECT_DATA_DELIVERY = 'DUE_DAYS_EXPECT_DATA_DELIVERY',
  DUE_DAYS_LOCATION_CONTRACTING = 'DUE_DAYS_LOCATION_CONTRACTING',
}
