apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ include "fdpg.fullname" . }}-mongo-secrets"
  labels:
  {{- include "fdpg.labels" . | nindent 4 }}
data:
  connectionString: {{ .Values.appConfig.environment.mongoConnectionString | b64enc | quote }}
