{
 "title": "FDPG-API outgoing requests",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "FDPG-API_local,\nFDPG-API_dev,\nFDPG-API_prelive,\nFDPG-API_prod"
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"$app\"},host)"
    }
   },
   { "name": "status", "label": "status code", "query": "2XX, 3XX, 4XX, 5XX" },
   { "name": "timesteps", "label": "Aggregation Step", "query": "30m" }
  ]
 },
 "panels": [
  {
   "title": "status codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (\n    increase(axios_client_requests_total{\n      app=~\"$app\",\n      host=~\"${host}\",\n      status=~\"${status:pipe}\"\n    }[$timesteps])\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (method, route, status) (increase(axios_client_requests_total{app=~\"$app\", status=~\"${status:pipe}\", host=~\"$host\"}[$timesteps]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Application logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"$app\"} \n| json \n| json method=\"req.method\", path=\"req.url\", service=\"context\"\n| context = \"OutboundHTTP\" \n| host =~ `${host:regex}`\n| line_format \"{{.application}} {{.level | ToUpper}} [{{.service}}] ({{.method}} {{.host}}) {{.msg}} ({{.duration}})\""
    }
   ]
  }
 ]
}