import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';
import { DataSourceStatus, DataSourceOrigin } from '../enum/data-source-status.enum';
import { DataSourceLanguage, DataSourceLanguageSchema } from './sub-schema/data-source-language.schema';

export type DataSourceDocument = DataSource & Document;

/**
 * DataSource Schema
 *
 * Represents a research study or data resource from external sources.
 * Stores metadata about studies including multilingual titles, descriptions,
 * and approval status for integration into the FDPG portal.
 */
@Schema({
  collection: 'data-sources',
  timestamps: true,
  versionKey: false,
})
export class DataSource {
  /**
   * MongoDB ObjectId (auto-generated by Mongoose).
   */
  _id?: string;

  /**
   * External identifier from the source system.
   * Examples: "NCT03464136", "DRKS00023385"
   */
  @Prop({
    type: String,
    required: true,
    unique: true,
    index: true,
  })
  externalIdentifier: string;

  /**
   * Origin/source of the data source.
   * Indicates which external system this data comes from.
   */
  @Prop({
    type: String,
    enum: Object.values(DataSourceOrigin),
    required: true,
    index: true,
  })
  origin: DataSourceOrigin;

  /**
   * Multilingual study titles.
   * Each entry contains a language code and the corresponding title text.
   */
  @Prop({
    type: [DataSourceLanguageSchema],
    required: true,
    default: [],
  })
  titles: DataSourceLanguage[];

  /**
   * Multilingual study descriptions.
   * Each entry contains a language code and the corresponding description text.
   */
  @Prop({
    type: [DataSourceLanguageSchema],
    required: true,
    default: [],
  })
  descriptions: DataSourceLanguage[];

  /**
   * Collection name the study belongs to.
   * Examples: "Individual Studies", "COVID-19", "Rare Diseases"
   */
  @Prop({
    type: String,
    required: true,
    index: true,
  })
  collection: string;

  /**
   * Numeric collection identifier from NFDI4Health.
   */
  @Prop({
    type: Number,
    required: true,
  })
  collectionId: number;

  /**
   * Study classification type.
   * Typically "Study" but can be other resource types.
   */
  @Prop({
    type: String,
    required: true,
  })
  classification: string;

  /**
   * Current approval status for display in the portal.
   */
  @Prop({
    type: String,
    enum: Object.values(DataSourceStatus),
    required: true,
    default: DataSourceStatus.PENDING,
    index: true,
  })
  status: DataSourceStatus;

  @Prop({
    type: Boolean,
    required: true,
    default: false,
  })
  active: boolean;

  /**
   * Date when the data source was approved for display.
   */
  @Prop({
    type: Date,
    required: false,
  })
  approvalDate?: Date;

  /**
   * Timestamp when the document was created (auto-managed by Mongoose).
   */
  createdAt?: Date;

  /**
   * Timestamp when the document was last updated (auto-managed by Mongoose).
   */
  updatedAt?: Date;
}

const DataSourceSchema = SchemaFactory.createForClass(DataSource);

export { DataSourceSchema };
