export type TemplateProposalEmailConditionKeys =
  | 'timestamp'
  | 'conditionProposalRejected'
  | 'conditionProposalRework'
  | 'conditionProposalFdpgCheck'
  | 'conditionFdpgCheckReminderForFdpg'
  | 'conditionProposalLocationCheck'
  | 'conditionProposalLocalUacCheck'
  | 'conditionProposalUacCheck'
  | 'conditionProposalLocationCheckDizForward'
  | 'conditionProposalUacReminder'
  | 'conditionProposalContracting'
  | 'conditionProposalContractSignedLocations'
  | 'conditionProposalContractSignedUser'
  | 'conditionProposalDataDelivery'
  | 'conditionProposalDataResearch'
  | 'conditionProposalDataReady'
  | 'conditionProposalDataReturn'
  | 'conditionProposalReport'
  | 'conditionProposalPublication'
  | 'conditionProposalRegistration'
  | 'conditionProposalFinished'
  | 'conditionProposalConcluded'
  | 'conditionProposalArchived'
  | 'conditionProposalUnlocked'
  | 'conditionProposalLocked'
  | 'conditionProposalReportCreate'
  | 'conditionProposalReportUpdate'
  | 'conditionProposalReportDelete'
  | 'conditionProposalPublicationCreate'
  | 'conditionProposalPublicationUpdate'
  | 'conditionProposalPublicationDelete'
  | 'DUE_DAYS_LOCATION_CHECK'
  | 'DUE_DAYS_LOCATION_CONTRACTING'
  | 'DUE_DAYS_EXPECT_DATA_DELIVERY'
  | 'conditionDeadlineFdpgCheckChanged'
  | 'deadlineFdpgCheckNewDate'
  | 'conditionDeadlineLocationCheckChanged'
  | 'deadlineLocationCheckNewDate'
  | 'conditionDeadlineLocationContractingChanged'
  | 'deadlineLocationContractingNewDate'
  | 'conditionDeadlineExpectedDataDeliveryChanged'
  | 'deadlineExpectedDataDeliveryNewDate'
  | 'conditionDeadlineExpectedDataCorruptChanged'
  | 'deadlineExpectedDataCorruptNewDate'
  | 'conditionDeadlineFinishedProjectChanged'
  | 'deadlineFinishedProjectNewDate';

export type TemplateEmailParamKeys =
  | Partial<TemplateProposalEmailConditionKeys>
  | 'projectAbbreviation'
  | 'projectLink'
  | 'projectResearchers'
  | 'firstName'
  | 'lastName';

export type EmailParameterMap = Partial<Record<TemplateProposalEmailConditionKeys, boolean | string | Date>>;
