export enum CacheKey {
  AllAdmins = 'CACHE_KEY_ALL_ADMINS',
  AllRoles = 'CACHE_KEY_ALL_ROLES',
  AllFdpgMember = 'CACHE_KEY_ALL_FDPG_MEMBER',
  AllDizMember = 'CACHE_KEY_ALL_DIZ_MEMBER',
  AllUacMember = 'CACHE_KEY_ALL_UAC_MEMBER',
  AllDataSourceMembers = 'CACHE_KEY_ALL_DATA_SOURCE_MEMBER',
  AllResearchers = 'CACHE_KEY_ALL_RESEARCHERS',
  AllUsers = 'CACHE_KEY_ALL_USERS',
  MiiLocations = 'CACHE_KEY_MII_LOCATIONS',
  MiiLocationsKeyLabel = 'CACHE_KEY_MII_LOCATIONS_KEY_LABEL',
  AllDmoUsers = 'CACHE_KEY_DMO_USERS',
  AcptResearchers = 'CACHE_KEY_ACPT_RESEARCHERS',
  AcptLocations = 'CACHE_KEY_ACPT_LOCATIONS',
}
